version: "3.8"

services:
  mqtt:
    image: eclipse-mosquitto:2
    container_name: mqtt
    ports:
      - "1856:1856"
      - "9001:9001"

  db:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: tpuser
      POSTGRES_PASSWORD: tppass
      POSTGRES_DB: tracking
    ports:
      - "5432:5432"

  backend:
    image: python:3.11
    container_name: backend
    working_dir: /app
    volumes:
      - ./backend:/app
    command: bash -c "pip install -r requirements.txt && uvicorn main:app --host 0.0.0.0 --port 8000"
    ports:
      - "8000:8000"
    depends_on:
      - db
      - mqtt